USE ATC_DB;

CREATE TABLE FLIGHT_STATUS_TYPE (
    Status_Code VARCHAR(20) PRIMARY KEY
);

INSERT INTO FLIGHT_STATUS_TYPE VALUES
('SCHEDULED'),
('APPROACHING'),
('HOLDING'),
('LANDED'),
('EMERGENCY');

CREATE TABLE EMERGENCY_TYPE (
    Emergency_Code VARCHAR(30) PRIMARY KEY
);

INSERT INTO EMERGENCY_TYPE VALUES
('MEDICAL'),
('ENGINE_FAILURE'),
('LOW_FUEL'),
('HIJACK');