USE ATC_DB;

DROP TABLE IF EXISTS FLIGHT_STATUS_LOG;
DROP TABLE IF EXISTS FLIGHT_CONTROLLER_ASSIGNMENT;
DROP TABLE IF EXISTS EMERGENCY_FLIGHT;
DROP TABLE IF EXISTS FLIGHT;

CREATE TABLE FLIGHT (
    Flight_ID INT PRIMARY KEY,
    Aircraft_ID INT NOT NULL,
    Current_Status VARCHAR(20) NOT NULL,
    Scheduled_Time DATETIME NOT NULL,
    Actual_Time DATETIME,
    Runway_ID INT,
    Gate_ID INT,
    FOREIGN KEY (Current_Status)
        REFERENCES FLIGHT_STATUS_TYPE(Status_Code),
    FOREIGN KEY (Aircraft_ID)
        REFERENCES AIRCRAFT(Aircraft_ID),
    FOREIGN KEY (Runway_ID)
        REFERENCES RUNWAY(Runway_ID),
    FOREIGN KEY (Gate_ID)
        REFERENCES GATE(Gate_ID)
);

CREATE TABLE EMERGENCY_FLIGHT (
    Flight_ID INT PRIMARY KEY,
    Emergency_Type VARCHAR(30) NOT NULL,
    Priority_Level INT NOT NULL CHECK (Priority_Level BETWEEN 1 AND 5),
    FOREIGN KEY (Flight_ID) REFERENCES FLIGHT(Flight_ID),
    FOREIGN KEY (Emergency_Type)
        REFERENCES EMERGENCY_TYPE(Emergency_Code)
);
CREATE TABLE FLIGHT_CONTROLLER_ASSIGNMENT (
    Assignment_ID INT PRIMARY KEY,
    Flight_ID INT NOT NULL,
    Controller_ID INT NOT NULL,
    Assigned_At DATETIME DEFAULT NOW(),
    FOREIGN KEY (Flight_ID) REFERENCES FLIGHT(Flight_ID),
    FOREIGN KEY (Controller_ID) REFERENCES CONTROLLER(Controller_ID),
    UNIQUE (Flight_ID, Controller_ID)
);